version: '3.8'

services:
  n8n:
    build: .  # Use the Dockerfile in this folder
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
    volumes:
      - ./data:/home/node/.n8n
      - ./mcp:/data/mcp